-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN birth_lat double precision;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN birth_lng double precision;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN birth_place character varying COLLATE pg_catalog."default" DEFAULT ''::character varying;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN birth_place_id character varying COLLATE pg_catalog."default" DEFAULT ''::character varying;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN birth_time timestamp with time zone;
